name: CI

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        # All the (nominally) supported Ruby versions
        ruby: ['2.5', '2.6', '2.7', '3.0', '3.1', '3.2', '3.3']

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run tests
      run: bundle exec rspec

    - name: Upload Coverage Report to CodeClimate
      # No sense uploading coverage for each Ruby version tested
      if: ${{matrix.ruby == '3.3'}}
      uses: paambaati/codeclimate-action@v5
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
