name: Upload coverage results to Code Climate

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
  upload:
    runs-on: ubuntu-latest

    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Generate and upload coverage report
        uses: paambaati/codeclimate-action@v5
        with:
          coverageCommand: bundle exec rspec
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
